# This is a basic workflow to help you get started with Actions

name: Deploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: ssh deploy
      env:
        SSH_PRIVATE_KEY: ${{ secrets.KEY }}
        REMOTE_HOST: ${{ secrets.hostname }}
        REMOTE_USER: ${{ secrets.user }}
        SOURCE: "server/"
        TARGET: "/home/REMOTE_USER/cit"
        KNOWN_HOSTS: ${{ secrets.knownhosts }}
      run: |
        mkdir -p $HOME/.ssh
        echo "$KNOWN_HOSTS" > $HOME/.ssh/known_hosts
        sudo chmod 600 $HOME/.ssh/known_hosts
        sudo chmod 600 $HOME/.ssh
        echo "$KEY" > sshkey
        sudo chmod 600 sshkey
        rsync -azPve "ssh -i sshkey" $SOURCE $REMOTE_USER@$REMOTE_HOST:$TARGET
